export const actionType = {
    SET_CITY: "SET_CITY",
    SET_NOW_INFO: "SET_NOW_INFO",
    SET_NEXT_DAYS: "SET_NEXT_DAYS",
    SET_MESSAGE: "SET_MESSAGE",
    FETCH_DATA_NOW: "FETCH_DATA_NOW",
    FETCH_DATA_NEXT_DAYS: "FETCH_DATA_NEXT_DAYS"
}